# NSD
nsd_hide_version: 'yes'
nsd_hide_identity: 'yes'
nsd_verbosity: 1
nsd_statistics: 86400
nsd_remote_control: 'yes'
nsd_port: 53

# Use predefined key
nsd_keys:
  - { name: seckey, algo: hmac-sha256, secret: "y6uRlBd1Y68eO9gIOEFGKmI5R1jg8Npq0iLMOSG2ViFQThjXgH0K0s4ffUOZlmMVtBQ+4Cmncasj7QysFhpPxA==" }

# .. Or generate a key
nsd_make_key: false
nsd_key_name: seckey
nsd_key_algo: hmac-sha256     # Currently hardcoded in dd command

nsd_masters:
  - { ip: "193.235.207.51@5353", key: "seckey" }

nsd_slaves:
  - { ip: "151.236.30.179@5353", key: "seckey" }

nsdzones:
  schmidbauer.cz:
    soa: ns.schmidbauer.cz. admin.schmidbauer.cz.
    serial: 2011010242
    refresh: 28800
    retry: 7200
    expire: 1209600
    ttl: 86400
    min_ttl: 86400
    records:
      - { type: 'NS',             value: 'ns' }
      - { type: 'NS',             value: 'ns2' }
      - { type: 'MX',             value: '10 mail.schmidbauer.cz.' }
      - { type: 'MX',             value: '20 mail2.schmidbauer.cz.' }
      - { type: 'TXT',            value: "v=spf1 mx:schmidbauer.cz -all" }
      - { type: 'CAA',            value: "128 issue 'letsencrypt.org'" }
      - { type: 'CAA',            value: "128 issuewild ';'" }
      - { name: 'files',          type: 'A',    value: "193.235.207.56" }
      - { name: 'files',          type: 'AAAA', value: "2a03:f80:420:193:235:207:56:1" }
      - { name: 'mon',            type: 'A',    value: "193.235.207.56" }
      - { name: 'mon',            type: 'AAAA', value: "2a03:f80:420:193:235:207:56:1" }
      - { name: 'man',            type: 'A',    value: "193.235.207.56" }
      - { name: 'man',            type: 'AAAA', value: "2a03:f80:420:193:235:207:56:1" }
      - { name: 'vpn',            type: 'A',    value: "193.235.207.56" }
      - { name: 'vpn',            type: 'AAAA', value: "2a03:f80:420:193:235:207:56:1" }
      - { name: 'www',            type: 'A',    value: "193.235.207.51" }
      - { name: 'www',            type: 'AAAA', value: "2a03:f80:420:193:235:207:51:1" }
      - { name: 'ns',             type: 'A',    value: "193.235.207.51" }
      - { name: 'ns',             type: 'AAAA', value: "2a03:f80:420:193:235:207:51:1" }
      - { name: 'mail',           type: 'A',    value: "193.235.207.51" }
      - { name: 'mail',           type: 'AAAA', value: "2a03:f80:420:193:235:207:51:1" }
      - { name: 'mail2',          type: 'A',    value: "151.236.30.179" }
      - { name: 'mail2',          type: 'AAAA', value: "2a03:f80:ed15:151:236:30:179:1" }
      - { name: 'ns2',            type: 'A',    value: "151.236.30.179" }
      - { name: 'ns2',            type: 'AAAA', value: "2a03:f80:ed15:151:236:30:179:1" }
      - { name: 'webmail',        type: 'A',    value: "193.235.207.56" }
      - { name: 'webmail',        type: 'AAAA', value: "2a03:f80:420:193:235:207:56:1" }
      - { name: '*',              type: 'A',    value: "193.235.207.51" }
      - { name: '*',              type: 'AAAA', value: "2a03:f80:420:193:235:207:51:1" }
      - { name: '_dmarc',         type: 'TXT',  value: "v=DMARC1;p=quarantine;pct=100;rua=mailto:postmaster@schmidbauer.cz;" }
      - { name: '20201114._domainkey',    type: 'TXT',    value: "v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDHMZuvph/1d1JvPdsXhCbR83tk0VBc5lh0/nJk5mfySSb3Jtol6TlTLhfN3xamalsCIEBVXIj/N/B5HSVGMFNCEu2nAvkw353o2jBuav3zIk3BHg2xu5dfhBcufLTUDgr84vz+1ijOU2a+N/50NCraeCq5CM0SZNdwY/nRnUKlvQIDAQAB;" }

      - { name: 'tlsa._dane.mail', type: 'TLSA', value: "3 1 1 d937fca6d98bcb97bf91b0cef59a068646c1f557e0edf628576692cc946ab621" }
      - { name: '_143._tcp.mail',  type: 'CNAME',value: "tlsa._dane.mail.schmidbauer.cz." }
      - { name: '_25._tcp.mail',   type: 'CNAME',value: "tlsa._dane.mail.schmidbauer.cz." }
      - { name: '_443._tcp.mail',  type: 'CNAME',value: "tlsa._dane.mail.schmidbauer.cz." }
      - { name: '_465._tcp.mail',  type: 'CNAME',value: "tlsa._dane.mail.schmidbauer.cz." }
      - { name: '_587._tcp.mail',  type: 'CNAME',value: "tlsa._dane.mail.schmidbauer.cz." }
      - { name: '_993._tcp.mail',  type: 'CNAME',value: "tlsa._dane.mail.schmidbauer.cz." }
      - { name: 'tlsa._dane.mail2', type: 'TLSA', value: "3 1 1 92c738b3168765bba09151bacce53f1fbc335ed240c5460459c211528fe82af5" }
      - { name: '_143._tcp.mail2',  type: 'CNAME',value: "tlsa._dane.mail2.schmidbauer.cz." }
      - { name: '_25._tcp.mail2',   type: 'CNAME',value: "tlsa._dane.mail2.schmidbauer.cz." }
      - { name: '_443._tcp.mail2',  type: 'CNAME',value: "tlsa._dane.mail2.schmidbauer.cz." }
      - { name: '_465._tcp.mail2',  type: 'CNAME',value: "tlsa._dane.mail2.schmidbauer.cz." }
      - { name: '_587._tcp.mail2',  type: 'CNAME',value: "tlsa._dane.mail2.schmidbauer.cz." }
      - { name: '_993._tcp.mail2',  type: 'CNAME',value: "tlsa._dane.mail2.schmidbauer.cz." }

      - { name: 'files.schmidbauer.cz',     type: 'SSHFP',  value: "4 1 6845f54633d096586cd7bdcad19ec20cc21e6cda" }
      - { name: 'files.schmidbauer.cz',     type: 'SSHFP',  value: "4 2 356ffb4137a05255837851005da41689bf5163639887fde7051bfd23a7cbf4a3" }
      - { name: 'mail.schmidbauer.cz',      type: 'SSHFP',  value: "4 1 a7c320684510be4c09f16278c0622188004c6bc7" }
      - { name: 'mail.schmidbauer.cz',      type: 'SSHFP',  value: "4 2 d12d63813a4ab592808ac4311a7d4afaca8250e45ef0b300821740b5d34e4d52" }
      - { name: 'man.schmidbauer.cz',       type: 'SSHFP',  value: "4 1 6845f54633d096586cd7bdcad19ec20cc21e6cda" }
      - { name: 'man.schmidbauer.cz',       type: 'SSHFP',  value: "4 2 356ffb4137a05255837851005da41689bf5163639887fde7051bfd23a7cbf4a3" }
      - { name: 'mon.schmidbauer.cz',       type: 'SSHFP',  value: "4 1 6845f54633d096586cd7bdcad19ec20cc21e6cda" }
      - { name: 'mon.schmidbauer.cz',       type: 'SSHFP',  value: "4 2 356ffb4137a05255837851005da41689bf5163639887fde7051bfd23a7cbf4a3" }
      - { name: 'ns.schmidbauer.cz',        type: 'SSHFP',  value: "4 1 a7c320684510be4c09f16278c0622188004c6bc7" }
      - { name: 'ns.schmidbauer.cz',        type: 'SSHFP',  value: "4 2 d12d63813a4ab592808ac4311a7d4afaca8250e45ef0b300821740b5d34e4d52" }
      - { name: 'vpn.schmidbauer.cz',       type: 'SSHFP',  value: "4 1 6845f54633d096586cd7bdcad19ec20cc21e6cda" }
      - { name: 'vpn.schmidbauer.cz',       type: 'SSHFP',  value: "4 2 356ffb4137a05255837851005da41689bf5163639887fde7051bfd23a7cbf4a3" }
      - { name: 'www.schmidbauer.cz',       type: 'SSHFP',  value: "4 1 a7c320684510be4c09f16278c0622188004c6bc7" }
      - { name: 'www.schmidbauer.cz',       type: 'SSHFP',  value: "4 2 d12d63813a4ab592808ac4311a7d4afaca8250e45ef0b300821740b5d34e4d52" }
      - { name: 'webmail.schmidbauer.cz',   type: 'SSHFP',  value: "4 1 a7c320684510be4c09f16278c0622188004c6bc7" }
      - { name: 'webmail.schmidbauer.cz',   type: 'SSHFP',  value: "4 2 d12d63813a4ab592808ac4311a7d4afaca8250e45ef0b300821740b5d34e4d52" }
      - { name: 'mail2.schmidbauer.cz',     type: 'SSHFP',  value: "4 1 9375f9ec283374bfc75397376681dc4ebd0a72b0" }
      - { name: 'mail2.schmidbauer.cz',     type: 'SSHFP',  value: "4 2 7afb602481b0a438058131499f7f607962bce6540fd458bd1dffce9e7138a7ce" }
      - { name: 'www2.schmidbauer.cz',      type: 'SSHFP',  value: "4 1 9375f9ec283374bfc75397376681dc4ebd0a72b0" }
      - { name: 'www2.schmidbauer.cz',      type: 'SSHFP',  value: "4 2 7afb602481b0a438058131499f7f607962bce6540fd458bd1dffce9e7138a7ce" }

unbound_acl:
  - 0.0.0.0/0 allow
  - ::0/0 allow

unbound_stub_zones:
  - { name: "schmidbauer.cz", stub_address: '127.0.0.1@53' }  # Pass to NSD

unbound_forward_zones:
  - { name: ".", forward_first: "yes", forward_addresses: "1.1.1.1,9.9.9.9" }

unbound_local_zones:
  - { name: "schmidbauer.cz", option: "nodefault" }

unbound_ipv6: 'yes'
unbound_auto_trust_anchor_file: /var/unbound/db/root.key
unbound_root_hints: /var/unbound/etc/root.hints
unbound_do_not_query_localhost: 'no'
unbound_remote_control: 'yes'
# unbound_use_tls: ns.schmidbauer.cz
unbound_tls_port: 853
unbound_hide_identity: 'yes'
unbound_hide_version: 'yes'
unbound_harden_glue: 'yes'
unbound_use_caps_for_id: 'yes'
unbound_deny_any: 'yes'
unbound_qname_minimisation: 'yes'
unbound_harden_dnssec_stripped: 'yes'
unbound_aggressive_nsec: 'yes'
unbound_log_queries: 'no'
unbound_log_replies: 'no'
unbound_use_adblocks: true
