# NSD
nsd_hide_version: 'yes'
nsd_hide_identity: 'yes'
nsd_verbosity: 1
nsd_statistics: 86400
nsd_remote_control: 'yes'
nsd_port: 5353

# Use predefined key
nsd_keys:
  - { name: seckey, algo: hmac-sha256, secret: "y6uRlBd1Y68eO9gIOEFGKmI5R1jg8Npq0iLMOSG2ViFQThjXgH0K0s4ffUOZlmMVtBQ+4Cmncasj7QysFhpPxA==" }

# .. Or generate a key
nsd_make_key: false
nsd_key_name: seckey
nsd_key_algo: hmac-sha256     # Currently hardcoded in dd command

nsd_masters:
  - { ip: "193.235.207.51@5353", key: "seckey" }

nsd_slaves:
  - { ip: "151.236.30.179@5353", key: "seckey" }

nsdzones:
  schmidbauer.cz:
    soa: ns.schmidbauer.cz admin.schmidbauer.cz
    serial: 2011010232
    refresh: 28800
    retry: 7200
    expire: 864000
    ttl: 86400
    min_ttl: 86400
    records:
      - { type: 'NS',                           value: 'ns.schmidbauer.cz.' }
      - { type: 'NS',                           value: 'ns2.schmidbauer.cz.' }
      - { type: 'MX',                           value: '10 mail.schmidbauer.cz.' }
      - { type: 'MX',                           value: '20 mail2.schmidbauer.cz.' }
      - { type: 'TXT',                          value: '"v=spf1 mx:schmidbauer.cz -all"' }
      - { name: 'schmidbauer.cz', type: 'CAA',  value: "128 issue 'letsencrypt.org'" }
      - { name: 'schmidbauer.cz', type: 'CAA',  value: "128 issuewild ';'" }
      - { name: 'files',          type: 'A',    value: "193.235.207.56" }
      - { name: 'files',          type: 'AAAA', value: "2a03:f80:420:193:235:207:56:1" }
      - { name: 'mon',            type: 'A',    value: "193.235.207.56" }
      - { name: 'mon',            type: 'AAAA', value: "2a03:f80:420:193:235:207:56:1" }
      - { name: 'man',            type: 'A',    value: "193.235.207.56" }
      - { name: 'man',            type: 'AAAA', value: "2a03:f80:420:193:235:207:56:1" }
      - { name: 'vpn',            type: 'A',    value: "193.235.207.56" }
      - { name: 'vpn',            type: 'AAAA', value: "2a03:f80:420:193:235:207:56:1" }
      - { name: 'www',            type: 'A',    value: "193.235.207.51" }
      - { name: 'www',            type: 'AAAA', value: "2a03:f80:420:193:235:207:51:1" }
      - { name: 'ns',             type: 'A',    value: "193.235.207.51" }
      - { name: 'ns',             type: 'AAAA', value: "2a03:f80:420:193:235:207:51:1" }
      - { name: 'mail',           type: 'A',    value: "193.235.207.51" }
      - { name: 'mail',           type: 'AAAA', value: "2a03:f80:420:193:235:207:51:1" }
      - { name: 'mail2',          type: 'A',    value: "151.236.30.179" }
      - { name: 'mail2',          type: 'AAAA', value: "2a03:f80:ed15:151:236:30:179:1" }
      - { name: 'ns2',            type: 'A',    value: "151.236.30.179" }
      - { name: 'ns2',            type: 'AAAA', value: "2a03:f80:ed15:151:236:30:179:1" }
      - { name: '*',              type: 'A',    value: "193.235.207.51" }
      - { name: '*',              type: 'AAAA', value: "2a03:f80:420:193:235:207:51:1" }
      - { name: '_dmarc',         type: 'TXT',  value: "'v=DMARC1;p=quarantine;pct=100;rua=mailto:postmaster@schmidbauer.cz;'" }

# Unbound
unbound_interfaces:
  - 0.0.0.0
  - 0.0.0.0@853
  - ::0@853

unbound_acl:
  - 0.0.0.0/0 allow
  - ::0/0 allow

unbound_stub_zones:
  - { name: "schmidbauer.cz", stub_address: '127.0.0.1@5353' }  # Pass to NSD

unbound_forward_zones:
  - { name: ".", forward_first: "yes", forward_addresses: "1.1.1.1,9.9.9.9" }

unbound_local_zones:
  - { name: "schmidbauer.cz", option: "nodefault" }

unbound_ipv6: 'yes'
unbound_auto_trust_anchor_file: /var/unbound/db/root.key
unbound_root_hints: /var/unbound/etc/root.hints
unbound_do_not_query_localhost: 'no'
unbound_remote_control: 'yes'
unbound_use_tls: ns2.schmidbauer.cz
unbound_tls_port: 853
unbound_hide_identity: 'yes'
unbound_hide_version: 'yes'
unbound_harden_glue: 'yes'
unbound_use_caps_for_id: 'yes'
unbound_deny_any: 'yes'
unbound_qname_minimisation: 'yes'
unbound_harden_dnssec_stripped: 'yes'
unbound_aggressive_nsec: 'yes'
unbound_log_queries: 'no'
unbound_log_replies: 'no'
