---
- name: Configure nsd
  hosts: all_hosts
  user: puffy
  become: true
  become_method: doas

  tasks:
    - name: "nsd - Install ldns-utils for DNSSEC"
      openbsd_pkg:
        name: ldns-utils
        state: present
      tags: nsd
      when: nsd_dnssec_sign_zones == true

    - name: "nsd - Generate secret"
      shell: dd if=/dev/urandom of=/dev/stdout status=none count=1 bs=64 | openssl base64 | tr -d '\n'
      register: nsd_secret_out
      no_log: true
      tags: nsd
      when: nsd_make_key == true

    - set_fact:
        nsd_keys:
          - { name: "{{ nsd_key_name }}", algo: "{{ nsd_key_algo }}", secret: "{{ nsd_secret_out.stdout }}" }
      when: nsd_make_key == True

    - name: "nsd - Configure /var/nsd/etc/nsd.conf"
      template:
        src: "nsd.conf.j2"
        dest: "/var/nsd/etc/nsd.conf"
      register: nsd_config
      tags: nsd

    - name: "nsd - Update secret"
      shell: nsd-control update_tsig {{ item.name }} "{{ item.secret }}"
      register: nsd_add_secret
      with_items: "{{ nsd_keys }}"
      tags: nsd
      when: nsd_make_key == true

    - name: "nsd - Control setup"
      shell: nsd-control-setup
      register: nsd_control_setup
      tags: nsd

    - name: "nsd - Create zones"
      template:
        src: "nsdzone.j2"
        dest: "/var/nsd/zones/master/{{ item.key }}.zone"
      with_dict: "{{ nsdzones }}"
      register: nsd_create_zones
      tags: nsd

    - name: "nsd - Check zones"
      shell: nsd-checkzone {{ item.key }} /var/nsd/zones/master/{{ item.key }}.zone
      register: nsd_check_zones
      with_dict: "{{ nsdzones }}"
      tags: nsd

    - name: "nsd - Sign zones"
      command: |
        export ZSK=$( /usr/local/bin/ldns-keygen -a "{{ item.nsd_dnssec_zsk_algo }} -b {{ item.nsd_dnssec_zsk_algo_bits }} {{ item.key }}" )
        export KSK=$( /usr/local/bin/ldns-keygen -a "{{ item.nsd_dnssec_ksk_algo }} -b {{ item.nsd_dnssec_ksk_algo_bits }} {{ item.key }}" )
        /usr/local/bin/ldns-signzone -n -s $(head -n 1000 /dev/urandom | sha256 | cut -b 1-16) master/{{ item.key }}.zone $ZSK $KSK
      args:
        chdir: /var/nsd/zones
      register: nsd_sign_zones
      when: nsd_dnssec_sign_zones == true
      with_dict: "{{ nsdzones }}"
      tags: nsd

    - name: "nsd - Check config"
      shell: nsd-checkconf /var/nsd/etc/nsd.conf
      register: nsd_config_check
      tags: nsd

    - name: "nsd - Ensure started and enabled"
      service:
        name: nsd
        state: started
        enabled: yes
      tags: nsd

    - name: "nsd - Reload config"
      shell: nsd-control reconfig
      register: nsd_reconfig
      tags: nsd

    - name: "nsd - Reload zones"
      shell: nsd-control reload
      register: nsd_config_reload
      tags: nsd
