---
- name: Configure nsd
  hosts: all_hosts
  user: puffy
  become: true
  become_method: doas

  tasks:
    - name: "nsd - Generate secret"
      shell: dd if=/dev/urandom of=/dev/stdout status=none count=1 bs=64 | openssl base64 | tr -d '\n'
      register: nsd_secret_out
      no_log: true
      tags: nsd
      when: nsd_make_key == True

    - set_fact:
        nsd_keys:
          - { name: "{{ nsd_key_name }}", algo: "{{ nsd_key_algo }}", secret: "{{ nsd_secret_out.stdout }}" }
      when: nsd_make_key == True

    - name: "nsd - Configure /var/nsd/etc/nsd.conf"
      template:
        src: "nsd.conf.j2"
        dest: "/var/nsd/etc/nsd.conf"
      register: nsd_config
      tags: nsd

    - name: "nsd - Update secret"
      shell: nsd-control update_tsig {{ item.name }} "{{ item.secret }}"
      register: nsd_add_secret
      with_items: "{{ nsd_keys }}"
      tags: nsd
      when: nsd_make_key == True

    - name: "nsd - Control setup"
      shell: nsd-control-setup
      register: nsd_control_setup
      tags: nsd

    - name: "nsd - Create zones"
      template:
        src: "nsdzone.j2"
        dest: "/var/nsd/zones/master/{{ item.key }}.zone"
      with_dict: "{{ nsdzones }}"
      register: nsd_create_zones
      tags: nsd

    - name: "nsd - Check config"
      shell: nsd-checkconf /var/nsd/etc/nsd.conf
      register: nsd_config_check
      tags: nsd

    - name: "nsd - Reload config if it's OK and changed"
      shell: nsd-control reconfig
      register: nsd_reconfig
      when: (nsd_config_check | bool) and nsd_config is changed
      tags: nsd

    - name: "nsd - Reload zones"
      shell: nsd-control reload
      register: nsd_config_reload
      when: (nsd_config_check | bool) and nsd_create_zones is changed
      tags: nsd
