# NSD
nsd_ips:
  - 127.0.0.1
  - 193.235.207.51
  - ::1
  - 2a03:f80:420:193:235:207:51:1

nsd_use_tls: ns.schmidbauer.cz

nsd_include_pattern: replicate_to

nsd_patterns:
  - { name: "replicate_to", key: "seckey", notify: "{{ nsd_slave_ipv4 }}", providexfr: "{{ nsd_slave_ipv4 }}" }

# Unbound
unbound_use_tls: ns.schmidbauer.cz

unbound_interfaces:
  - 2a03:f80:420:193:235:207:51:2
