# NSD
nsd_ips:
  - 127.0.0.1
  - 151.236.30.179
  - ::1
  - 2a03:f80:ed15:151:236:30:179:1

# nsd_use_tls: ns2.schmidbauer.cz

nsd_include_pattern: replicate_from

nsd_patterns:
  - { name: "replicate_from", key: "seckey", allownotify: "{{ nsd_master_ipv4 }}", requestxfr: "{{ nsd_master_ipv4 }}" }

# Unbound
unbound_use_tls: ns2.schmidbauer.cz

unbound_interfaces:
  - 2a03:f80:ed15:151:236:30:179:2
