# NSD
nsd_ips:
  - 127.0.0.1
  - 151.236.30.179
  - ::1
  - 2a03:f80:ed15:151:236:30:179:1

nsd_use_tls: ns2.schmidbauer.cz

nsd_include_pattern: replicate_from

nsd_patterns:
  - { name: "replicate_from", key: "seckey", allownotify: "151.236.30.179@5353", requestxfr: "151.236.30.179@5353" }

# Unbound
unbound_use_tls: ns2.schmidbauer.cz
